FROM ubuntu as remote-agent-ansible

RUN apt update && apt install -y openssh-server

# Password is `test`
#RUN useradd -m -p '$6$RUo.h3DaGrgbdgM$KCuaiYyOA3kq.JfTPklfPXkYdenAPsanUux/sUjyJd/bXK1MpTdivWiUdJka3cNPFLhvBxVdrU1hpHdjBXrOg0' -s /bin/bash remote_user \
#	&& mkdir /home/remote_user/.ssh \
#	&& chmod 700 /home/remote_user/.ssh

#COPY ssh/remote-key.pub /home/remote_user/.ssh/authorized_keys

#RUN chown remote_user:remote_user -R /home/remote_user/.ssh/ \
# && chmod 600 /home/remote_user/.ssh/authorized_keys

#RUN ssh-keygen -A && mkdir -p /run/sshd

RUN apt update && apt install -y ansible default-jre git curl \
	&& curl -sL https://deb.nodesource.com/setup_14.x -o nodesource_setup.sh \
	&& sh ./nodesource_setup.sh \
	&& apt install -y nodejs

COPY agent.jar agent.jar
